branch-defaults:
  master:
    environment: development
    group_suffix: null
global:
  application_name: trainingjournal
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: PHP 8.1 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
